/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace ERC1155ETH {
  export type UserDataStruct = {
    nullifier: BigNumberish;
    identityCreationTimestamp: BigNumberish;
    identityCounter: BigNumberish;
  };

  export type UserDataStructOutput = [BigNumber, BigNumber, BigNumber] & {
    nullifier: BigNumber;
    identityCreationTimestamp: BigNumber;
    identityCounter: BigNumber;
  };

  export type TransitionDataStruct = {
    newRoot: BytesLike;
    transitionTimestamp: BigNumberish;
    proof: BytesLike;
  };

  export type TransitionDataStructOutput = [string, BigNumber, string] & {
    newRoot: string;
    transitionTimestamp: BigNumber;
    proof: string;
  };
}

export declare namespace VerifierHelper {
  export type ProofPointsStruct = {
    a: [BigNumberish, BigNumberish];
    b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]];
    c: [BigNumberish, BigNumberish];
  };

  export type ProofPointsStructOutput = [
    [BigNumber, BigNumber],
    [[BigNumber, BigNumber], [BigNumber, BigNumber]],
    [BigNumber, BigNumber]
  ] & {
    a: [BigNumber, BigNumber];
    b: [[BigNumber, BigNumber], [BigNumber, BigNumber]];
    c: [BigNumber, BigNumber];
  };
}

export interface ERC1155ETHInterface extends utils.Interface {
  functions: {
    "PROOF_SIGNALS_COUNT()": FunctionFragment;
    "SELECTOR()": FunctionFragment;
    "UPGRADE_INTERFACE_VERSION()": FunctionFragment;
    "ZERO_DATE()": FunctionFragment;
    "__ERC1155ETH_init(address,address,string)": FunctionFragment;
    "balanceOf(address,uint256)": FunctionFragment;
    "balanceOfBatch(address[],uint256[])": FunctionFragment;
    "identityProofVerifier()": FunctionFragment;
    "implementation()": FunctionFragment;
    "initTimestamp()": FunctionFragment;
    "isApprovedForAll(address,address)": FunctionFragment;
    "isNullifierUsed(uint256)": FunctionFragment;
    "mint(bytes32,uint256,address,uint256,(uint256,uint256,uint256),(uint256[2],uint256[2][2],uint256[2]))": FunctionFragment;
    "mintWithRootTransition((bytes32,uint256,bytes),uint256,address,uint256,(uint256,uint256,uint256),(uint256[2],uint256[2][2],uint256[2]))": FunctionFragment;
    "mintWithSimpleRootTransition((bytes32,uint256,bytes),uint256,address,uint256,(uint256,uint256,uint256),(uint256[2],uint256[2][2],uint256[2]))": FunctionFragment;
    "nullifiers(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "safeBatchTransferFrom(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "safeTransferFrom(address,address,uint256,uint256,bytes)": FunctionFragment;
    "setApprovalForAll(address,bool)": FunctionFragment;
    "setURI(string)": FunctionFragment;
    "state()": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "uri(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "PROOF_SIGNALS_COUNT"
      | "SELECTOR"
      | "UPGRADE_INTERFACE_VERSION"
      | "ZERO_DATE"
      | "__ERC1155ETH_init"
      | "balanceOf"
      | "balanceOfBatch"
      | "identityProofVerifier"
      | "implementation"
      | "initTimestamp"
      | "isApprovedForAll"
      | "isNullifierUsed"
      | "mint"
      | "mintWithRootTransition"
      | "mintWithSimpleRootTransition"
      | "nullifiers"
      | "owner"
      | "proxiableUUID"
      | "renounceOwnership"
      | "safeBatchTransferFrom"
      | "safeTransferFrom"
      | "setApprovalForAll"
      | "setURI"
      | "state"
      | "supportsInterface"
      | "transferOwnership"
      | "upgradeToAndCall"
      | "uri"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "PROOF_SIGNALS_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "SELECTOR", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ZERO_DATE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "__ERC1155ETH_init",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfBatch",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "identityProofVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isNullifierUsed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [
      BytesLike,
      BigNumberish,
      string,
      BigNumberish,
      ERC1155ETH.UserDataStruct,
      VerifierHelper.ProofPointsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mintWithRootTransition",
    values: [
      ERC1155ETH.TransitionDataStruct,
      BigNumberish,
      string,
      BigNumberish,
      ERC1155ETH.UserDataStruct,
      VerifierHelper.ProofPointsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mintWithSimpleRootTransition",
    values: [
      ERC1155ETH.TransitionDataStruct,
      BigNumberish,
      string,
      BigNumberish,
      ERC1155ETH.UserDataStruct,
      VerifierHelper.ProofPointsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "nullifiers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeBatchTransferFrom",
    values: [string, string, BigNumberish[], BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [string, boolean]
  ): string;
  encodeFunctionData(functionFragment: "setURI", values: [string]): string;
  encodeFunctionData(functionFragment: "state", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "uri", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "PROOF_SIGNALS_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SELECTOR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ZERO_DATE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "__ERC1155ETH_init",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityProofVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isNullifierUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintWithRootTransition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintWithSimpleRootTransition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nullifiers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeBatchTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setURI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uri", data: BytesLike): Result;

  events: {
    "ApprovalForAll(address,address,bool)": EventFragment;
    "Initialized(uint64)": EventFragment;
    "MagicTokenMinted(address,uint256,uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "TransferBatch(address,address,address,uint256[],uint256[])": EventFragment;
    "TransferSingle(address,address,address,uint256,uint256)": EventFragment;
    "URI(string,uint256)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ApprovalForAll"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MagicTokenMinted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferBatch"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferSingle"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "URI"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface ApprovalForAllEventObject {
  account: string;
  operator: string;
  approved: boolean;
}
export type ApprovalForAllEvent = TypedEvent<
  [string, string, boolean],
  ApprovalForAllEventObject
>;

export type ApprovalForAllEventFilter = TypedEventFilter<ApprovalForAllEvent>;

export interface InitializedEventObject {
  version: BigNumber;
}
export type InitializedEvent = TypedEvent<[BigNumber], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface MagicTokenMintedEventObject {
  to: string;
  tokenId: BigNumber;
  value: BigNumber;
  nullifier: BigNumber;
}
export type MagicTokenMintedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  MagicTokenMintedEventObject
>;

export type MagicTokenMintedEventFilter =
  TypedEventFilter<MagicTokenMintedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface TransferBatchEventObject {
  operator: string;
  from: string;
  to: string;
  ids: BigNumber[];
  values: BigNumber[];
}
export type TransferBatchEvent = TypedEvent<
  [string, string, string, BigNumber[], BigNumber[]],
  TransferBatchEventObject
>;

export type TransferBatchEventFilter = TypedEventFilter<TransferBatchEvent>;

export interface TransferSingleEventObject {
  operator: string;
  from: string;
  to: string;
  id: BigNumber;
  value: BigNumber;
}
export type TransferSingleEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  TransferSingleEventObject
>;

export type TransferSingleEventFilter = TypedEventFilter<TransferSingleEvent>;

export interface URIEventObject {
  value: string;
  id: BigNumber;
}
export type URIEvent = TypedEvent<[string, BigNumber], URIEventObject>;

export type URIEventFilter = TypedEventFilter<URIEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface ERC1155ETH extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ERC1155ETHInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    PROOF_SIGNALS_COUNT(overrides?: CallOverrides): Promise<[BigNumber]>;

    SELECTOR(overrides?: CallOverrides): Promise<[BigNumber]>;

    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<[string]>;

    ZERO_DATE(overrides?: CallOverrides): Promise<[BigNumber]>;

    __ERC1155ETH_init(
      identityProofVerifier_: string,
      state_: string,
      uri_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    balanceOf(
      account: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    balanceOfBatch(
      accounts: string[],
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    identityProofVerifier(overrides?: CallOverrides): Promise<[string]>;

    implementation(overrides?: CallOverrides): Promise<[string]>;

    initTimestamp(overrides?: CallOverrides): Promise<[BigNumber]>;

    isApprovedForAll(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isNullifierUsed(
      nullifier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    mint(
      registrationRoot_: BytesLike,
      tokenId_: BigNumberish,
      receiver_: string,
      currentDate_: BigNumberish,
      userData_: ERC1155ETH.UserDataStruct,
      zkPoints_: VerifierHelper.ProofPointsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    mintWithRootTransition(
      transitionData_: ERC1155ETH.TransitionDataStruct,
      tokenId_: BigNumberish,
      receiver_: string,
      currentDate_: BigNumberish,
      userData_: ERC1155ETH.UserDataStruct,
      zkPoints_: VerifierHelper.ProofPointsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    mintWithSimpleRootTransition(
      transitionData_: ERC1155ETH.TransitionDataStruct,
      tokenId_: BigNumberish,
      receiver_: string,
      currentDate_: BigNumberish,
      userData_: ERC1155ETH.UserDataStruct,
      zkPoints_: VerifierHelper.ProofPointsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    nullifiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    safeBatchTransferFrom(
      from: string,
      to: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    safeTransferFrom(
      from: string,
      to: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setURI(
      newURI_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    state(overrides?: CallOverrides): Promise<[string]>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    uri(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;
  };

  PROOF_SIGNALS_COUNT(overrides?: CallOverrides): Promise<BigNumber>;

  SELECTOR(overrides?: CallOverrides): Promise<BigNumber>;

  UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<string>;

  ZERO_DATE(overrides?: CallOverrides): Promise<BigNumber>;

  __ERC1155ETH_init(
    identityProofVerifier_: string,
    state_: string,
    uri_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  balanceOf(
    account: string,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  balanceOfBatch(
    accounts: string[],
    ids: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  identityProofVerifier(overrides?: CallOverrides): Promise<string>;

  implementation(overrides?: CallOverrides): Promise<string>;

  initTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  isApprovedForAll(
    account: string,
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isNullifierUsed(
    nullifier: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  mint(
    registrationRoot_: BytesLike,
    tokenId_: BigNumberish,
    receiver_: string,
    currentDate_: BigNumberish,
    userData_: ERC1155ETH.UserDataStruct,
    zkPoints_: VerifierHelper.ProofPointsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  mintWithRootTransition(
    transitionData_: ERC1155ETH.TransitionDataStruct,
    tokenId_: BigNumberish,
    receiver_: string,
    currentDate_: BigNumberish,
    userData_: ERC1155ETH.UserDataStruct,
    zkPoints_: VerifierHelper.ProofPointsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  mintWithSimpleRootTransition(
    transitionData_: ERC1155ETH.TransitionDataStruct,
    tokenId_: BigNumberish,
    receiver_: string,
    currentDate_: BigNumberish,
    userData_: ERC1155ETH.UserDataStruct,
    zkPoints_: VerifierHelper.ProofPointsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  nullifiers(arg0: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  safeBatchTransferFrom(
    from: string,
    to: string,
    ids: BigNumberish[],
    values: BigNumberish[],
    data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  safeTransferFrom(
    from: string,
    to: string,
    id: BigNumberish,
    value: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setApprovalForAll(
    operator: string,
    approved: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setURI(
    newURI_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  state(overrides?: CallOverrides): Promise<string>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: string,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  uri(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    PROOF_SIGNALS_COUNT(overrides?: CallOverrides): Promise<BigNumber>;

    SELECTOR(overrides?: CallOverrides): Promise<BigNumber>;

    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<string>;

    ZERO_DATE(overrides?: CallOverrides): Promise<BigNumber>;

    __ERC1155ETH_init(
      identityProofVerifier_: string,
      state_: string,
      uri_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    balanceOf(
      account: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfBatch(
      accounts: string[],
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    identityProofVerifier(overrides?: CallOverrides): Promise<string>;

    implementation(overrides?: CallOverrides): Promise<string>;

    initTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    isApprovedForAll(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isNullifierUsed(
      nullifier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    mint(
      registrationRoot_: BytesLike,
      tokenId_: BigNumberish,
      receiver_: string,
      currentDate_: BigNumberish,
      userData_: ERC1155ETH.UserDataStruct,
      zkPoints_: VerifierHelper.ProofPointsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    mintWithRootTransition(
      transitionData_: ERC1155ETH.TransitionDataStruct,
      tokenId_: BigNumberish,
      receiver_: string,
      currentDate_: BigNumberish,
      userData_: ERC1155ETH.UserDataStruct,
      zkPoints_: VerifierHelper.ProofPointsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    mintWithSimpleRootTransition(
      transitionData_: ERC1155ETH.TransitionDataStruct,
      tokenId_: BigNumberish,
      receiver_: string,
      currentDate_: BigNumberish,
      userData_: ERC1155ETH.UserDataStruct,
      zkPoints_: VerifierHelper.ProofPointsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    nullifiers(arg0: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    safeBatchTransferFrom(
      from: string,
      to: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    safeTransferFrom(
      from: string,
      to: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setURI(newURI_: string, overrides?: CallOverrides): Promise<void>;

    state(overrides?: CallOverrides): Promise<string>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    uri(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ApprovalForAll(address,address,bool)"(
      account?: string | null,
      operator?: string | null,
      approved?: null
    ): ApprovalForAllEventFilter;
    ApprovalForAll(
      account?: string | null,
      operator?: string | null,
      approved?: null
    ): ApprovalForAllEventFilter;

    "Initialized(uint64)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "MagicTokenMinted(address,uint256,uint256,uint256)"(
      to?: string | null,
      tokenId?: BigNumberish | null,
      value?: null,
      nullifier?: null
    ): MagicTokenMintedEventFilter;
    MagicTokenMinted(
      to?: string | null,
      tokenId?: BigNumberish | null,
      value?: null,
      nullifier?: null
    ): MagicTokenMintedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "TransferBatch(address,address,address,uint256[],uint256[])"(
      operator?: string | null,
      from?: string | null,
      to?: string | null,
      ids?: null,
      values?: null
    ): TransferBatchEventFilter;
    TransferBatch(
      operator?: string | null,
      from?: string | null,
      to?: string | null,
      ids?: null,
      values?: null
    ): TransferBatchEventFilter;

    "TransferSingle(address,address,address,uint256,uint256)"(
      operator?: string | null,
      from?: string | null,
      to?: string | null,
      id?: null,
      value?: null
    ): TransferSingleEventFilter;
    TransferSingle(
      operator?: string | null,
      from?: string | null,
      to?: string | null,
      id?: null,
      value?: null
    ): TransferSingleEventFilter;

    "URI(string,uint256)"(
      value?: null,
      id?: BigNumberish | null
    ): URIEventFilter;
    URI(value?: null, id?: BigNumberish | null): URIEventFilter;

    "Upgraded(address)"(implementation?: string | null): UpgradedEventFilter;
    Upgraded(implementation?: string | null): UpgradedEventFilter;
  };

  estimateGas: {
    PROOF_SIGNALS_COUNT(overrides?: CallOverrides): Promise<BigNumber>;

    SELECTOR(overrides?: CallOverrides): Promise<BigNumber>;

    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    ZERO_DATE(overrides?: CallOverrides): Promise<BigNumber>;

    __ERC1155ETH_init(
      identityProofVerifier_: string,
      state_: string,
      uri_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    balanceOf(
      account: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfBatch(
      accounts: string[],
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    identityProofVerifier(overrides?: CallOverrides): Promise<BigNumber>;

    implementation(overrides?: CallOverrides): Promise<BigNumber>;

    initTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    isApprovedForAll(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isNullifierUsed(
      nullifier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mint(
      registrationRoot_: BytesLike,
      tokenId_: BigNumberish,
      receiver_: string,
      currentDate_: BigNumberish,
      userData_: ERC1155ETH.UserDataStruct,
      zkPoints_: VerifierHelper.ProofPointsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    mintWithRootTransition(
      transitionData_: ERC1155ETH.TransitionDataStruct,
      tokenId_: BigNumberish,
      receiver_: string,
      currentDate_: BigNumberish,
      userData_: ERC1155ETH.UserDataStruct,
      zkPoints_: VerifierHelper.ProofPointsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    mintWithSimpleRootTransition(
      transitionData_: ERC1155ETH.TransitionDataStruct,
      tokenId_: BigNumberish,
      receiver_: string,
      currentDate_: BigNumberish,
      userData_: ERC1155ETH.UserDataStruct,
      zkPoints_: VerifierHelper.ProofPointsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    nullifiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    safeBatchTransferFrom(
      from: string,
      to: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    safeTransferFrom(
      from: string,
      to: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setURI(
      newURI_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    state(overrides?: CallOverrides): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    uri(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    PROOF_SIGNALS_COUNT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SELECTOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    UPGRADE_INTERFACE_VERSION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ZERO_DATE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    __ERC1155ETH_init(
      identityProofVerifier_: string,
      state_: string,
      uri_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    balanceOf(
      account: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOfBatch(
      accounts: string[],
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    identityProofVerifier(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    implementation(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initTimestamp(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isApprovedForAll(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isNullifierUsed(
      nullifier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mint(
      registrationRoot_: BytesLike,
      tokenId_: BigNumberish,
      receiver_: string,
      currentDate_: BigNumberish,
      userData_: ERC1155ETH.UserDataStruct,
      zkPoints_: VerifierHelper.ProofPointsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    mintWithRootTransition(
      transitionData_: ERC1155ETH.TransitionDataStruct,
      tokenId_: BigNumberish,
      receiver_: string,
      currentDate_: BigNumberish,
      userData_: ERC1155ETH.UserDataStruct,
      zkPoints_: VerifierHelper.ProofPointsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    mintWithSimpleRootTransition(
      transitionData_: ERC1155ETH.TransitionDataStruct,
      tokenId_: BigNumberish,
      receiver_: string,
      currentDate_: BigNumberish,
      userData_: ERC1155ETH.UserDataStruct,
      zkPoints_: VerifierHelper.ProofPointsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    nullifiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    safeBatchTransferFrom(
      from: string,
      to: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    safeTransferFrom(
      from: string,
      to: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setURI(
      newURI_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    state(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    uri(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
